### ISSUE TITLE
Usage of "grep -P" in the script

### ISSUE THREAD

**Issue by sacheendra** [robisonsantos/evm#11]
"grep -P" is used in the script at a lot of places. This does not work with the grep included in Max OS X. 

I have changed it to "grep -E" and it worked for my purposes, which is to list available versions and install the required version. 

Are there any cases where perl specific things are used. If not, can all usages of "grep -P" be changed to "grep -E".

**Comment by robisonsantos** [comment]
Hi, I believe the -P was introduced to to solve mac incompatibilities, but
since I'm not a mac user I wasn't able to test it before approving the
changes.

I'll run some tests with -E on other systems and if everything goes ok I'll
make the changes.

Thanks,

- Robison

On Sat, Oct 17, 2015 at 3:04 PM, Sacheendra talluri <
notifications@github.com> wrote:

> "grep -P" is used in the script at a lot of places. This does not work
> with the grep included in Max OS X.
>
> I have changed it to "grep -E" and it worked for my purposes, which is to
> list available versions and install the required version.
>
> Are there any cases where perl specific things are used. If not, can all
> usages of "grep -P" be changed to "grep -E".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robisonsantos/evm/issues/11>.
>



-- 
Robison W R Santos

**Comment by robisonsantos** [comment]
Replaced grep -P with grep -E.
