### ISSUE TITLE
Installing RabbitMQ?

### ISSUE THREAD

**Issue by nsweeting** [robisonsantos/evm#30]
Hi there,

Slightly off-topic, but I am trying to figure out the best way to install RabbitMQ using an erlang version installed with evm. 

If I download the .deb package for rabbitmq-server, it seems to have issues recognizing the fact that erlang is installed - just not through apt-get. Specifically, it seems to not have the following "satisfiable dependencies": erlang-nox >= 1:19.3 and esl-erlang >= 1:19.3

Any guidance would be appreciated!

**Comment by robisonsantos** [comment]
Since you are using .deb to install RabbitMQ, it may be looking for libs in
the wrong place (system's /usr/lib) or some other standard location.

EVM installs erlang in your home directory (/home/.evm).

You might need to point your installation path to .deb somehow. I'd try
setting up LD_LIBRARY_PATH and trying again.

I didn't test it yet but can try it soon, just maybe not today.

**Comment by robisonsantos** [comment]
Just looked at the RabbitMQ page and some other pages. The `erlang-nox` (Erlang No X) is a meta/dummy package that install all parts of erlang that does not require 'X' (https://packages.debian.org/sid/erlang-nox)

 `esl-erlang` is also a meta package which "is a file containg the complete installation: it includes the Erlang/OTP platform and all of its applications. The erlang package is a frontend to a number of smaller packages. Currently we support both erlang and esl-erlang." (https://www.erlang-solutions.com/resources/download.html)

Those are dependencies of the `.deb` file - https://www.rabbitmq.com/install-debian.html - but because evm builds and installs an erlang from tarball, you won't have those.

I think the best alternative when using EVM would be to follow this: https://www.rabbitmq.com/install-generic-unix.html

**Comment by robisonsantos** [comment]
Just got it working in my box:

```
robison@ghost:/home/robison/Apps/rabbitmq_server-3.7.3|⇒  evm installed
Installed Erlang versions on this system

=* 20.1
19.2
19.1
19.0
18.3
18.1

------
=* : current and default
=> : current
 * : default

robison@ghost:/home/robison/Apps/rabbitmq_server-3.7.3|⇒  sbin/rabbitmq-server 

  ##  ##
  ##  ##      RabbitMQ 3.7.3. Copyright (C) 2007-2018 Pivotal Software, Inc.
  ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
  ######  ##
  ##########  Logs: /home/robison/Apps/rabbitmq_server-3.7.3/var/log/rabbitmq/rabbit@ghost.log
                    /home/robison/Apps/rabbitmq_server-3.7.3/var/log/rabbitmq/rabbit@ghost_upgrade.log

              Starting broker...
 completed with 0 plugins.

```

**Comment by nsweeting** [comment]
Great - worked with the generic install - thanks @robisonsantos
